WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT = (960, 480)
DISPLAY_SIZE = DISPLAY_WIDTH, DISPLAY_HEIGHT = (512, 384)
FULL_SCREEN = False
MOUSE_VISIBLE = False
FULL_SCREEN = False
TILE_SIZE = [16, 16]
CHUNK_SIZE = 8
FPS = 60
